### ISSUE TITLE
Can't compile via g++

### ISSUE THREAD

**Issue by Nauchnik** [saeednj/CDCL-Crypto#1]
My OS is Ubuntu 20.04, g++ version is 10.2.0.
When I run 
_make minisat_
from the folder
CDCL-Crypto/src/
it gives me the following errors:
_/home/oleg/solvers_cdcl/CDCL-Crypto/src/core/SolverTypes.h:85:16: error: friend declaration of ‘Minisat::Lit mkLit(Minisat::Var, bool)’ specifies default arguments and isn’t a definition [-fpermissive]
   85 |     friend Lit mkLit(Var var, bool sign = false);
      |                ^~~~~
/home/oleg/solvers_cdcl/CDCL-Crypto/src/core/SolverTypes.h:93:14: error: friend declaration of ‘Minisat::Lit Minisat::mkLit(Minisat::Var, bool)’ specifies default arguments and isn’t the only declaration [-fpermissive]
   93 | inline  Lit  mkLit     (Var var, bool sign) { Lit p; p.x = var + var + (int)sign; return p; }_

Could you please help me with that?

**Comment by saeednj** [comment]
Hello @Nauchnik 

Thanks for pointing out this issue.

The MapleSAT code base was using an older version of Minisat, which caused this problem.

I have fixed the code. I have tested it on Ubuntu 20.04, g++ version 9.3.0. It should be working with g++ 10.2 as well, but please feel free to re-open the issue, if it doesn't work with g++ 10.2.

Thanks
